apiVersion: apps/v1
kind: Deployment
metadata:
 name: myweb-dep
spec:
 replicas: 4
 selector:
  matchLabels:
   env: web
 template:
  metadata:
   name: myweb-pod
   labels:
    env: web
  spec:
   containers:
   - name: myweb-con
     image: shhhhhubhammmm/web-php-dev:v1